booktitle: バベルフレンズ
dsr: ["@Omegamega"]
date: 2017-04-09
history: [["2017-04-09"], ["2017-04-29"]]
source: ["https://github.com/np-complete/TechBookFes02"]
titlepage: titlepage.tex
coverimage: null
pdfmaker:
  coverimage: null
